name: Create Repository and Assign Issues

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUBB_TOKEN }}
      ISSUE_TITLE: ok
      ISSUE_CONTENT_FILEPATH: docs/*
    steps:
    - name: Checkout Repositoryy
      uses: actions/checkout@v2

    - name: Create repository for new user
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUBB_TOKEN }}
        script: |
          const repoName = 'reposbhgvd'
          const response = await github.repos.createForAuthenticatedUser({ name: repoName })
          console.log(response.data.html_url)
          core.setOutput('repo_url', response.data.html_url)
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc jq

    - name: Loop through files in folder
      run: |
         for file in ./docs/*.docx
         do
          title=$(basename "$file")
          body=$(pandoc "$file")
          json=$(echo '{}' | jq --arg title "$title" --arg body "$body" '.title=$title | .body=$body')
          curl -H "Authorization: token ${{ secrets.GITHUBB_TOKEN }}" \
               -H "Content-Type: application/json" \
               -d "$json" \
               "https://api.github.com/repos/${{ github.repository }}/issues"
          done
      shell: bash
