name: New User Onboarding

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'New user GitHub username'

jobs:
  create_repo_and_assign_issues:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Create repository for new user
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUBB_TOKEN }}
        script: |
          const repoName = 'onboarding-offboarding-' + new Date().getTime()
          const response = await github.repos.createForAuthenticatedUser({ name: repoName })
          console.log(response.data.html_url)
          core.setOutput('repo_url', response.data.html_url)

    - name: Assign issues to new repository
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.GITHUBB_TOKEN }}
        repository: onboarding-offboarding-1679042409761
        event-type: "assign-issues"
        client-payload: |
            {
              "docsPath": "docs",
              "assignees": ["suryaraghava80"]
            }
