name: Create Repository and Assign Issues

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUBB_TOKEN }}
      ISSUE_TITLE: ok
    steps:
    - name: Checkout Repositoryy
      uses: actions/checkout@v2

    - name: Create repository for new user
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUBB_TOKEN }}
        script: |
          const repoName = 'repository-seconDhbjnVblok'
          const response = await github.repos.createForAuthenticatedUser({ name: repoName })
          console.log(response.data.html_url)
          core.setOutput('repo_url', response.data.html_url)


    - name: Find Word and PDF Files
      run: |
        # Use the 'find' command to locate Word and PDF files
        # Adjust the path and file types to match your requirements
        FILES=$(find docs/ -type f -name "*.docx" -o -name "*.pdf")
        echo $FILES      

    - name: Create Issues    
      uses: peter-evans/create-issue-from-file@v1      
      with:
        GITHUB_TOKEN: $GITHUB_TOKEN
        file-path: $FILES
        ISSUE_TITLE: $ISSUE_TITLE
        title-prefix: "Issue: "
        body-prefix: "This issue was automatically created based on the files: "
        assignees: octocat
