name: Create Repository and Assign Issues

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repositoryy
      uses: actions/checkout@v2

    - name: Create Repository
      uses: peter-evans/create-repo@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: my-new-repo
        visibility: private

    - name: Find Word and PDF Files
      run: |
        # Use the 'find' command to locate Word and PDF files
        # Adjust the path and file types to match your requirements
        FILES=$(find /docs -type f -name "*.docx" -o -name "*.pdf")
        echo $FILES

    - name: Create Issues
      uses: peter-evans/create-issue-from-file@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        file-path: $FILES
        title-prefix: "Issue: "
        body-prefix: "This issue was automatically created based on the file: "
        assignees: octocat
