name: Create New Repo with Issues

on:
  push:
    branches:
      - main     
jobs:
  create_repo:
    runs-on: ubuntu-latest  
    steps:
      - name: Prompt for Name
        id: input_step
        run: |
          echo "::set-output name=name::$(read -p 'What is your name? ' name; echo $name)"    
      - name: Checkout Code
        uses: actions/checkout@v2     

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Create New Repository
        run: |
          repo_name="my-new-repo-${{ env.INPUT_NAME }}"
          description="This is my new repository."
          curl -H "Authorization: token ${{ secrets.GITHUBB_TOKEN }}" \
               -d "{\"name\":\"$repo_name\",\"description\":\"$description\"}" \
               "https://api.github.com/user/repos"
        env:
          INPUT_NAME: ${{ steps.input_step.outputs.name }}               

      - name: Clone New Repository
        run: |
          git clone "https://github.com/suryaraghava80/my-new-repo-.git"
          cd "my-new-repo-"

      - name: Loop through files in folder
        run: |
          for file in ./docs/*.docx
          do
            title=$(basename "$file")
            body=$(pandoc "$file")
            json=$(echo '{}' | jq --arg title "$title" --arg body "$body" '.title=$title | .body=$body')
            curl -H "Authorization: token ${{ secrets.GITHUBB_TOKEN }}" \
                 -H "Content-Type: application/json" \
                 -d "$json" \
                 "https://api.github.com/repos/suryaraghava80/my-new-repo-/issues"
          done
        shell: bash
